### ISSUE TITLE
Basic Page Design

### ISSUE THREAD

**Issue by nfcopier** [nfcopier/TheLordOfTheRepos#1]
We need to hash out the basic style/design of our pages.

**Comment by Natonator** [comment]
Do we want to have someone draw out a design? I was thinking when we build,
we break up the implementation of different pages to each person, with 1
master css file including css files for different parts. That way we can
avoid some merge conflicts.

**Comment by nfcopier** [comment]
Check out the other issues I've added.

I would like to know who, in our group, has artistic ability.
