### ISSUE TITLE
Allow users to update their profile data

### ISSUE THREAD

**Issue by HGunther** [nfcopier/TheLordOfTheRepos#27]

**Comment by HGunther** [comment]
Allow users to update their profile data
Upon visiting the "Profile" view users should see a form that allows them to edit
the following fields:
Username
Full Name
Bio
Website
The update profile form on the profile page should contain the data that is
currently stored in the database and when updated should update with the latest
data from the database

**Comment by nfcopier** [comment]
Resolved with @61e2b5a5b67a6be4fb0bcda7df1aa04f69127b58.
