### ISSUE TITLE
Allow users to save searches

### ISSUE THREAD

**Issue by HGunther** [nfcopier/TheLordOfTheRepos#28]

**Comment by HGunther** [comment]
Allow users to save searches
After entering a search term the user should see the search results page along
with a button that allows them to save their search
If the user clicks on this save button their saved searches list should be updated
(could be on the same page or you could take the user to a saved searches page)

**Comment by Natonator** [comment]
I'll take this one

**Comment by HGunther** [comment]
We need to get this one done to work on the others, so I worked on it in class today and I think I finished it. I'm pushing my code now. I also added the ability to check if a search exists before adding new duplicate searches.

**Comment by HGunther** [comment]
Apparently we can't both be assigned this. If you like my code lets check this one off.

**Comment by Natonator** [comment]
That's fine, let's go with yours. I didn't come today because I was
throwing up all night. I'll work on another part today.
