### ISSUE TITLE
Allow users to view saved search results

### ISSUE THREAD

**Issue by HGunther** [nfcopier/TheLordOfTheRepos#29]

**Comment by HGunther** [comment]
Allow users to view saved search results
If a user clicks on one of their saved searches it should take them to the search
results page where they can view the results of the saved search

**Comment by Natonator** [comment]
How are we coming along with this? I think I could have this up tonight.

**Comment by mabraithwaite** [comment]
You can if you want, I would need a different task if you do though.

**Comment by Natonator** [comment]
Yeah, that is fine, trade for the delete search?

**Comment by Natonator** [comment]
I have pushed my changes, it looks like it is working.

**Comment by HGunther** [comment]
This looks good. I'm going to close this issue. Thanks
